stages:
  - build
  - test

# =================================================================================================================================
# Stage "build"
# v>9 artifacts: name: "${CI_PIPELINE_ID}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
# =================================================================================================================================
build_linadv:
  stage: build 
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
    - rm -rf tests/dirx_* || true
  script: 
    - cd tests; pwd
    - python build_tests.py -buildhdf5 0 -case 100-200 
  after_script:
    - pwd 
  cache:
    key: ${CI_BUILD_NAME}
    paths:
    - tests/dirx_*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/dirx_*

#--------------------------------------------------------------------------------------------------------------------------------
build_maxwell:
  stage: build 
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
    - rm -rf tests/dirx_* || true
  script: 
    - cd tests; pwd
    - python build_tests.py -buildhdf5 0 -case 200-300 
  after_script:
    - pwd 
  cache:
    key: ${CI_BUILD_NAME}
    paths:
    - tests/dirx_*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/dirx_*

#--------------------------------------------------------------------------------------------------------------------------------
build_mhd:
  stage: build 
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
    - rm -rf tests/dirx_* || true
  script: 
    - cd tests; pwd
    - python build_tests.py -buildhdf5 0 -case 300-400 
  after_script:
    - pwd 
  cache:
    key: ${CI_BUILD_NAME}
    paths:
    - tests/dirx_*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/dirx_*


# =================================================================================================================================
# Stage "test" 
# v>9 artifacts: name: "${CI_PIPELINE_ID}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
# =================================================================================================================================
