stages:
  - build
  - short_runs

# =================================================================================================================================
# Stage "build"
# v>9 artifacts: name: "${CI_PIPELINE_ID}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
# =================================================================================================================================
build_linadv:
  stage: build 
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
    - rm -rf tests/dirx_* || true
  script: 
    - cd tests; pwd
    - python build_tests.py -p 4 -stage 0 -buildhdf5 0 -case 100-199 
  after_script:
    - pwd 
  cache:
    key: ${CI_BUILD_NAME}
    paths:
    - tests/dirx_1[0-9][0-9]*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/dirx_*

#--------------------------------------------------------------------------------------------------------------------------------
build_maxwell:
  stage: build 
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
    - rm -rf tests/dirx_* || true
  script: 
    - cd tests; pwd
    - python build_tests.py -p 4 -stage 0 -buildhdf5 0 -case 200-299 
  after_script:
    - pwd 
  cache:
    key: ${CI_BUILD_NAME}
    paths:
    - tests/dirx_2[0-9][0-9]*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/log.*

#--------------------------------------------------------------------------------------------------------------------------------
build_mhd:
  stage: build 
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
    - rm -rf tests/dirx_* || true
  script: 
    - cd tests; pwd
    - python build_tests.py -p 4 -stage 0 -buildhdf5 0 -case 300-399 
  after_script:
    - pwd 
  cache:
    key: ${CI_BUILD_NAME}
    paths:
    - tests/dirx_3[0-9][0-9]*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/log.*


# =================================================================================================================================
# Stage "short_runs"
# =================================================================================================================================
short_runs_linadv:
  stage: short_runs
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
  script: 
    - cd tests; pwd
    - python build_tests.py -p 2 -stage 2 -case 100-199 
  after_script:
    - pwd 
  cache:
    key: build_linadv
    paths:
    - tests/dirx_1[0-9][0-9]*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/freestream/log.LINADV*


#--------------------------------------------------------------------------------------------------------------------------------
short_runs_mhd:
  stage: short_runs
  tags:
    - vm_linux
  only:
    - testCI
  before_script:
    - module list
  script: 
    - cd tests; pwd
    - python build_tests.py -p 2 -stage 2 -case 300-399 
  after_script:
    - pwd 
  cache:
    key: build_mhd
    paths:
    - tests/dirx_3[0-9][0-9]*
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - tests/freestream/log.MHD*
